@startuml
entity Operation {
    beginTime
    endTime
    keyword
    address
    description
}
entity OperationCrew {
    isDeleted
}

entity Training {
    date
    title: String
}
entity TrainingGroup {
    
}

entity Person {
    firstName
    lastName
    picture
}
entity Vehicle {
    name
    picture
    isActive
    maxOperationCrewNumber
}
entity Group {
    name
    color
}

entity VehicleUser {
    email
    password
}
entity PublicUser {
    token
    name
    roles
}
entity PersonalUser {
    email
    password
    roles
    firstName
    lastName
}

enum Category {
    Brand
    THL
    Sicherheitswache
    UG-ÖEL
    Hochwasser
}
enum Status {
    Aktiv
    Jugend
    Passiv
    ausgetreten
}

Operation --|| Category
Operation ||--o{ OperationCrew
OperationCrew }o--|{ Person
OperationCrew }o--|| Vehicle

Training ||--|{ TrainingGroup
TrainingGroup }o--|{ Person
TrainingGroup }o--|| Group

Person }o--o{ Group
Person --|| Status

VehicleUser }o--|| Vehicle
@enduml