@startuml
left to right direction

actor "AlarmServer" as alarm

actor "Gruppenführer" as leader

rectangle FeuerwehrApp {
    ' Callout added automatically
    usecase "Einsatz hinzufügen" as AddCallout

    ' Callouts
    usecase "Einsätze anzeigen" as ViewCallouts
    usecase "Einsatz-Mannschaft eintragen" as SelectCrew

    ' Trainings
    usecase "Übungen anzeigen" as ViewTrainings
    usecase "Übung hinzufügen" as AddTraining
    usecase "Übungsteilnehmer eintragen" as SelectTrainingParticipants
}

alarm -- (AddCallout)
leader -- (ViewCallouts)
leader -- (SelectCrew)

leader -- (ViewTrainings)
leader -- (SelectTrainingParticipants)
leader -- (AddTraining)

@enduml
