@startuml
left to right direction

actor "Gruppenführer" as leader

rectangle FeuerStatistik {
    usecase "Daten exportieren" as Export
    usecase "Person bearbeiten" as EditPeople
    usecase "Gruppe bearbeiten" as EditGroups
    usecase "Fahrzeug bearbeiten" as EditVehicle
    usecase "Passwort ändern" as EditPwd

    usecase "Login" as Login

    (Export) <.. (Login) : extend
    (EditPeople) <.. (Login) : extend
    (EditGroups) <.. (Login) : extend
    (EditVehicle) <.. (Login) : extend
    (EditPwd) <.. (Login) : extend
}

leader -- (Export)
leader -- (EditPeople)
leader -- (EditGroups)
leader -- (EditVehicle)
leader -- (EditPwd)
@enduml
