@startuml

abstract class Benutzer << Entity >> {
    name
    email
    passwort
}
class Gruppenführer << Entity >>
class Admin << Entity >>
class Alarmfax << Entity >>

Benutzer <|-- Alarmfax
Benutzer <|-- Gruppenführer
Gruppenführer <|-- Admin

@enduml