@startuml

abstract class Benutzer << Entity >> {
    name
    email
    passwort
}
class Gruppenführer << Entity >>
class Alarmfax << Entity >>

Benutzer <|-- Alarmfax
Benutzer <|-- Gruppenführer

@enduml
