name: CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.devcontainer/'
      - '.github/'
      - 'docs/'
      - 'tools/'
      - '.editorconfig'
      - '.git*'
      - '**.md'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - run: npm ci
