name: CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.devcontainer/**'
      - 'docs/**'
      - 'tools/**'
      - '.editorconfig'
      - '.git*'
      - '**.md'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Generate empty configuration
        run: echo "export default {};" > ./src/firebase/config.ts
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Generate empty configuration
        run: echo "export default {};" > ./src/firebase/config.ts
      
      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint -- --no-fix
